# Generated by Django 4.2.3 on 2023-07-28 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_place_host'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['updated', 'created']},
        ),
        migrations.AddField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 7, 28, 9, 43, 18, 769578, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
