# Generated by Django 4.2.3 on 2023-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_place_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='files',
            field=models.ManyToManyField(related_name='topics', to='base.file'),
        ),
    ]
