# Generated by Django 4.2.3 on 2023-08-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name', '-created']},
        ),
        migrations.AddField(
            model_name='place',
            name='accessPassword',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
